-- Devin Review follow-up on PR #21:
--   1. Postgres `PRIMARY KEY (key, actor_id, method, path)` forbids NULL
--      actor_id (PK implies NOT NULL), breaking the documented anonymous
--      route support. Switch to a surrogate `id` PK + unique EXPRESSION
--      index that COALESCEs NULL actor_id to a sentinel UUID, so anonymous
--      requests with the same (key, method, path) correctly collide.
--   2. The middleware now uses "claim-then-update" to close the TOCTOU
--      race between SELECT and INSERT; that needs a unique constraint the
--      handler can `ON CONFLICT DO NOTHING` against.

-- Add surrogate id column so we can drop the composite PK.
ALTER TABLE idempotent_responses ADD COLUMN IF NOT EXISTS id UUID;
UPDATE idempotent_responses SET id = gen_random_uuid() WHERE id IS NULL;
ALTER TABLE idempotent_responses ALTER COLUMN id SET NOT NULL;

-- Drop the old composite PK (name is auto-generated by Postgres).
ALTER TABLE idempotent_responses DROP CONSTRAINT IF EXISTS idempotent_responses_pkey;
ALTER TABLE idempotent_responses ADD PRIMARY KEY (id);

-- Unique expression index over (key, COALESCE(actor_id, NULL_SENTINEL), method, path)
-- so ON CONFLICT DO NOTHING works and NULL actor_ids collide as expected.
CREATE UNIQUE INDEX IF NOT EXISTS idx_idempotent_responses_lookup
  ON idempotent_responses (
    key,
    COALESCE(actor_id, '00000000-0000-0000-0000-000000000000'),
    method,
    path
  );
